print("Content-Type: text/html\n")
print("<!DOCTYPE html>")
print("<html lang=\"en\">")
print("    <head>")
print("        <title>Hello</title>")
print("    </head>")
print("    <body>")
print("        <h1>Hello, World!!</h1>")
print("    </body>")
print("</html>")